### ISSUE TITLE
@ExtendWith on Spock Execution not implemented

### ISSUE THREAD

**Issue by kenjdavidson** [xvik/spock-junit5#44]
Thanks for this library, it's worked wonders for sharing functionality between JUnit and Spock.  In this instance though, I'm curious if you know of a way to get this working.

We have a JUnit extension where we use the `executionContext.root().getStore()` to create (effectively) singleton logic for all tests within the context.  We then spawn off child objects based on the implementation of other annotations for Class or Method level.  Giving us the ability to have:

```
root object
  -  class object
    - method object
``

When implementing this library for Spock it is creating a new execution context for each class, but is not assigning it a root, therefore removing the ability for us to have a `root object` across all Spock tests.

This looks to be the result of only implementing the `visitSpec` method and not the `start` method creating a root context.  Although I see why this was done, I'm curious if there is any way around it with the current implementation?  Essentially we need an annotation at the Class level to some how not be re-created.

I realize the difficulty here is determining whether the class level annotation is:
- for the context
- for the class

Although if you could add your own 

```
interface ExecutionExtension extends Extension {}
```

And if the initial extension is this type, it becomes the root for the subsequent registries.

**Comment by xvik** [comment]
Interesting case. I indeed can create root context before all tests (in the start method of global extension), but this would be a single root context for all tests (like in junit;  in fact, junit has a more complex context tree but spock lacks all other concepts requiring additional contexts like suites, nested and template tests )

I don't understand the part about more specific contexts: if I understand correcty, you suggest to have some test class annotation which will trigger (sub)root context creation for all subsequent tests. But what if tests will run in parallel? Besides, tests should not rely on execution order (don't remember for spock, but, as I remember, in junit, tests order is intentionally not determinable).

If you use the root context in junit exrtension then it would always be "the root for all tests". I don't see why you need some more specific (sub)contexts.

And I can't suggest any wourkaround except manually managing some static global state in extension.

As a summary: I will add parent context suport (one for all tests), but I don't see (for now) use cases for more specific sub-contexts driven by annotation (but, maybe, you'll convince me). Can't promise this very soon as I have few other things on stack before it, but I'll try to do it sooner.

**Comment by kenjdavidson** [comment]
To give you some context, these are our integration tests and initially we were bringing up a really expensive environment at the start of all tests.  The environment has its own built in separation, so its not a huge deal (for the most part) if we only have one of them for all tests.    Essentially it works like this:

1. before all tests bring up the expensive environment.  This environment is just a container (say a database) server (DB1)
2. before each test bring up a less expensive context inside DB1 (DB1.table_random).  Run the method test on this table.
3. after each test drop the table.

Each of these methods has:
- db info
- table info

injected into it.  Running these tests in parallel aren't an issue.

In some cases we DO need a new DB since we need to test, say for example, a system table.  Obviously doing this would blow up all other tests.  So in this case we have @NewTestEnvironment:

1. before all bring up DB1
2. before each look for `@NewTestEnvironment`, if this exists bring up a new DB.  Regardless, build the new table.
3. after each look for `@NewTestEnvironment`, if it exists just drop the whole DB (table included. Otherwise drop the table in root DB.

At this point, we're making substantially less complex environments, instead of 1 per test we're making 1 per class, so it's. start.  But it could be a little better.

**Comment by xvik** [comment]
But this case needs only root and class contexts:

- root storage: default environment (DB0)
- (optional, driven by custom annotation) class storage: custom environment (DB1)

method level logic is the same for both cases: `getStorage(NS).get("db.env").createTable()` which will bring either new or default db and where table would be created.

Maybe I misunderstand you initially, but I thought you need some additional storage level: root -- "something else" -- class -- method. But, as I can see, you only miss a root storage and so it would be enough if I add only it.

**Comment by kenjdavidson** [comment]
Nope. Root, class, method.  I wa slaying around with it and it seems to be pretty straight forward. Internal tests and my tests are working well.

**Comment by xvik** [comment]
link PR #45

**Comment by kenjdavidson** [comment]
Thank you! I appreciate the help and guidance.

**Comment by xvik** [comment]
[released](https://github.com/xvik/spock-junit5/releases/tag/1.2.0)
